# Generated by Codex on 2026-06-15

import uuid

import django.db.models.deletion
from django.db import migrations, models

import apps.common.encryption


class Migration(migrations.Migration):
    dependencies = [
        ("credentials", "0004_rename_instagram_personal_to_login"),
        ("organizations", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SmtpCredential",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "credentials",
                    apps.common.encryption.EncryptedJSONField(
                        default=dict,
                        help_text="Encrypted JSON containing SMTP host, port, username, password, and sender details.",
                    ),
                ),
                ("is_configured", models.BooleanField(default=False)),
                ("tested_at", models.DateTimeField(blank=True, null=True)),
                (
                    "test_result",
                    models.CharField(
                        choices=[("success", "Success"), ("failure", "Failure"), ("untested", "Untested")],
                        default="untested",
                        max_length=20,
                    ),
                ),
                ("last_error", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organization",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="smtp_credential",
                        to="organizations.organization",
                    ),
                ),
            ],
            options={
                "db_table": "credentials_smtp_credential",
            },
        ),
    ]
