# Generated by Codex on 2026-06-06

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("credentials", "0005_smtpcredential"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("organizations", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SmtpTestLog",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("recipient_email", models.EmailField(max_length=254)),
                ("from_email", models.EmailField(max_length=254)),
                ("host", models.CharField(max_length=255)),
                ("port", models.PositiveIntegerField(default=587)),
                (
                    "status",
                    models.CharField(choices=[("success", "Success"), ("failure", "Failure")], max_length=20),
                ),
                ("error", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="smtp_test_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="smtp_test_logs",
                        to="organizations.organization",
                    ),
                ),
                (
                    "smtp_credential",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="test_logs",
                        to="credentials.smtpcredential",
                    ),
                ),
            ],
            options={
                "db_table": "credentials_smtp_test_log",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="smtptestlog",
            index=models.Index(fields=["organization", "created_at"], name="idx_smtp_log_org_time"),
        ),
        migrations.AddIndex(
            model_name="smtptestlog",
            index=models.Index(fields=["status", "created_at"], name="idx_smtp_log_status"),
        ),
    ]
